{{- $nimVlm := index .Values.nimOperator "nim-vlm" -}}
{{- if and (.Capabilities.APIVersions.Has "apps.nvidia.com/v1alpha1") (eq $nimVlm.enabled true) }}
apiVersion: apps.nvidia.com/v1alpha1
kind: NIMCache
metadata:
  name: {{ $nimVlm.service.name }}-cache
  annotations:
    helm.sh/resource-policy: keep
spec:
  source:
    ngc:
      modelPuller: "{{ $nimVlm.image.repository }}:{{ $nimVlm.image.tag }}"
      pullSecret: {{ .Values.imagePullSecret.name }}
      authSecret: {{ .Values.ngcApiSecret.name }}
  storage:
    pvc:
      create: {{ $nimVlm.storage.pvc.create | default true }}
      size: {{ $nimVlm.storage.pvc.size | default "50Gi" }}
      storageClass: {{ $nimVlm.storage.pvc.storageClass | default "default" }}
      volumeAccessMode: {{ $nimVlm.storage.pvc.volumeAccessMode | default "ReadWriteMany" }}
  resources: {}
---
apiVersion: apps.nvidia.com/v1alpha1
kind: NIMService
metadata:
  name: {{ $nimVlm.service.name }}
spec:
  image:
    repository: {{ $nimVlm.image.repository }}
    tag: {{ $nimVlm.image.tag }}
    pullPolicy: {{ $nimVlm.image.pullPolicy | default "IfNotPresent" }}
    pullSecrets:
      - {{ .Values.imagePullSecret.name }}
  authSecret: {{ .Values.ngcApiSecret.name }}
  storage:
    nimCache:
      name: {{ $nimVlm.service.name }}-cache
  env:
{{ toYaml $nimVlm.env | nindent 4 }}
  replicas: {{ $nimVlm.replicas | default 1 }}
  {{- with $nimVlm.nodeSelector }}
  nodeSelector:
{{ toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.nimOperator.draResources.enabled }}
  draResources:
{{ toYaml $nimVlm.draResources | nindent 4 }}
{{- end }}
{{- if not .Values.nimOperator.draResources.enabled }}
  resources:
{{ toYaml $nimVlm.resources | nindent 4 }}
{{- end }}
  expose:
{{ toYaml $nimVlm.expose | nindent 4 }}
{{- end }}