nimOperator:
  draResources:
    enabled: true
    name: "rag-claim"
  nim-llm:
    resources:
      limits:
        nvidia.com/gpu: 1
      requests:
        nvidia.com/gpu: 1
    draResources:
      - claimCreationSpec:
          devices:
            - name: nimllm-gpu
              count: 1
              deviceClassName: gpu.nvidia.com
              driverName: gpu.nvidia.com
              attributeSelectors:
                - key: driverVersion
                  op: GreaterThanOrEqual
                  value:
                    versionValue: "550.127.8"
              capacitySelectors:
                - key: memory
                  op: GreaterThanOrEqual
                  value: 40Gi
  nvidia-nim-llama-32-nv-embedqa-1b-v2:
    draResources:
    - resourceClaimName: rag-claim
  nvidia-nim-llama-32-nv-rerankqa-1b-v2:
    draResources:
    - resourceClaimName: rag-claim
nv-ingest:
  nimOperator:
    draResources:
      enabled: true
      name: "rag-claim"
    embedqa:
      enabled: false
    page_elements:
      draResources:
      - resourceClaimName: rag-claim
    graphic_elements:
      draResources:
      - resourceClaimName: rag-claim
    table_structure:
      draResources:
      - resourceClaimName: rag-claim
    nemoretriever_ocr_v1:
      draResources:
      - resourceClaimName: rag-claim
  milvus:
    image:
      all:
        repository: milvusdb/milvus
        tag: v2.6.5-gpu
    standalone:
      resources:
        limits:
          nvidia.com/gpu: 0
      extraEnv:
      - name: CUDA_VISIBLE_DEVICES
        value: "0"