apiVersion: v2
appVersion: v2.4.0-rc2
dependencies:
- condition: nv-ingest.enabled
  name: nv-ingest
  repository: https://helm.ngc.nvidia.com/nvidia/nemo-microservices
  version: 26.1.1
- condition: elasticsearch.enabled
  name: eck-stack
  repository: https://helm.elastic.co
  version: 0.17.0
- condition: elasticsearch.enabled
  name: eck-operator
  repository: https://helm.elastic.co
  version: 3.2.0
- condition: zipkin.enabled
  name: zipkin
  repository: https://zipkin.io/zipkin-helm
  version: 0.4.0
- condition: opentelemetry-collector.enabled
  name: opentelemetry-collector
  repository: https://open-telemetry.github.io/opentelemetry-helm-charts
  version: 0.130.2
- condition: kube-prometheus-stack.enabled
  name: kube-prometheus-stack
  repository: https://prometheus-community.github.io/helm-charts
  version: 76.3.0
description: An end to end Helm chart for the NVIDIA RAG Blueprint
name: nvidia-blueprint-rag
type: application
version: v2.4.0-rc2
